### ISSUE TITLE
The 'medium' is an incorrect font-weight and fonts with it doesn't preloaded

### ISSUE THREAD

**Issue by TrueXakeP** [CreateJS/PreloadJS#246]
First sorry for my english.

I have a font 'Merel'. I use it in my web-app in two weights 500 and 300.

With PreloadJS 1.0.0 this JS code:
```js
var fldr = new createjs.FontLoader({
        src: [
            "/fonts/merel/Merel-Medium.woff2",
            "/fonts/merel/Merel-Light.woff2"
        ],
        type "font"
    }, true);
fldr.load();
```
produces this CSS:
```css
@font-face {
    font-family: 'Merel';
    font-style: normal;
    font-weight: 300;
    src: local('Merel Light'), url('/fonts/merel/Merel-Light.woff2') format('woff2');
}
@font-face {
    font-family: 'Merel';
    font-style: normal;
    font-weight: medium;
    src: local('Merel Medium'), url('/fonts/merel/Merel-Medium.woff2') format('woff2');
}
```
But regarding to [MDN](https://developer.mozilla.org/en/docs/Web/CSS/font-weight) the `medium` is an incorrect value for the `font-weight` property. And I see in the console of my `Chromium 64.0.3254.0` and `Firefox Nightly 59.0a1` that Merel-Medium is loaded only after I make a visible element that uses it. And also I see that "Flash Of Unstyled Text" in that moment.

This is also happened when I specify 'medium' as a weight in a css or object definition.
```JS
{
    src: [ {
        src: "url(/fonts/merel/Merel-Medium.woff2) format('woff2')",
        family: "Merel",
        weight: "medium",
        style: "normal"
    }, /*....*/ ],
    type: "font"
}
```
When I specify font-weight as the '500' then the font preloads correct. But in that case I can not use short array definition as a list of files.

[The MDN](https://developer.mozilla.org/en/docs/Web/CSS/font-weight) says that correct font weights are: `normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900`
Also the PHPStorm tells me that 'medium' is invalid value for the 'font-weight' property when I try to use it in my styles.

**Comment by TrueXakeP** [comment]
I just discovered that as a workaround I can just rename the file `Merel-Medium.woff2` to `Merel-500.woff2` but in that case a 'Merel 500' will be required first as a local font.
```css
@font-face {
    font-family: 'Merel';
    font-style: normal;
    font-weight: 500;
    src: local('Merel 500'), url('/fonts/merel/Merel-500.woff2') format('woff2');
}
```
